CREATE TABLE recipes (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         dish_name VARCHAR(255) NOT NULL
);

CREATE TABLE ingredients (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             recipe_id BIGINT NOT NULL,
                             ingredient_name VARCHAR(255) NOT NULL,
                             amount VARCHAR(100),
                             FOREIGN KEY (recipe_id) REFERENCES recipes(id)
);